name: Build MiraiPurpur 1.20.1
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@main
      - name: Set up JDK (GraalVM)
        uses: graalvm/setup-graalvm@main
        with:
          java-version: 17
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Gradle Cache
        uses: actions/cache@v3
        id: gradle-cache
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-maven-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-java-${{ matrix.java }}
      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          chmod +x gradlew
      - name: Patch
        run: ./gradlew -Dorg.gradle.jvmargs="-Dfile.encoding=UTF-8 -Dgraal.CompilerConfiguration=community -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true -Dgraal.SpeculativeGuardMovement=true -Dgraal.WriteableCodeCache=true --add-modules jdk.incubator.vector" applyPatches --stacktrace --no-daemon
      - name: ReobfPaperclipJar
        run: ./gradlew -Dorg.gradle.jvmargs="-Dfile.encoding=UTF-8 -Dgraal.CompilerConfiguration=community -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true -Dgraal.SpeculativeGuardMovement=true -Dgraal.WriteableCodeCache=true --add-modules jdk.incubator.vector" createReobfPaperclipJar --stacktrace --no-daemon
      - name: Release
        if: github.ref_name == 'purpur/1.20.1'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "MiraiPurpur-1.20.1"
          automatic_release_tag: "purpur-1.20.1"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: build/libs/Mirai-paperclip-1.20.1-R0.1-SNAPSHOT-reobf.jar
          prerelease: false
